{% set name = "component-contribution" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/component-contribution-{{ version }}.tar.gz
  sha256: 50b5257cfbcaa663c99df49f3f8a995dde6064407fe8099a9ef168f164633ba0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - equilibrator-cache ~=0.5.1
    - scipy >=1.11
    - path ~=16.7
    - uncertainties ~=3.1

test:
  imports:
    - component_contribution
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/component-contribution
  summary: Standard reaction Gibbs energy estimation for biochemical reactions.
  license: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/equilibrator/component-contribution

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
