{% set name = "component-contribution" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/component-contribution-{{ version }}.tar.gz
  sha256: 9948283bcaa91ba5b4f25b21789c8916b8cc41086406b138df2d7edab319161b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=41
    - setuptools-scm
    - wheel
    - setuptools-git-versioning >=2.0,<3
    - pip
  run:
    - python >=3.9
    - equilibrator-cache ~=0.6.1
    - path >=16.7
    - uncertainties >=3.1

test:
  imports:
    - component_contribution
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/component-contribution
  summary: A method for estimating the standard reaction Gibbs energy of biochemical reactions
  license: MIT
  license_file: LICENSE
  dev_url: https://gitlab.com/equilibrator/component-contribution

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
    
