{% set name = "component-contribution" %}
{% set version = "0.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/component-contribution-{{ version }}.tar.gz
  sha256: ee99f18f56ffaaf899162c3d11c9e6c3b61c390e5c1b124bcb411bd2d91673e0

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - appdirs ~=1.4
    - diskcache ~=5.0
    - equilibrator-cache ~=0.4.1
    - httpx ~=0.16
    - path ~=15.0
    - periodictable ~=1.5
    - python >=3.6
    - pyzenodo3 ~=1.0
    - tenacity ~=6.2
    - uncertainties ~=3.1

test:
  imports:
    - component_contribution
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/component-contribution
  summary: Standard reaction Gibbs energy estimation for biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    Standard reaction Gibbs energy estimation for biochemical reactions.  For more information on the method behind component-contribution, please view our open access paper:

    Noor E, Haraldsdóttir HS, Milo R, Fleming RMT (2013) Consistent Estimation of Gibbs Energy Using Component Contributions, PLoS Comput Biol 9:e1003098, DOI: 10.1371/journal.pcbi.1003098

    Please, cite this paper if you publish work that uses component-contribution.
  dev_url: https://gitlab.com/equilibrator/component-contribution

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
