{% set name = "component-contribution" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/component-contribution-{{ version }}.tar.gz
  sha256: 8beccd6fbd5514d00ac93bc139e63912358f23f1da4000036c3c11d3ae23f38f

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps

requirements:
  host:
    - pip
    - python >=3.9
  run:
    - python >=3.9
    - equilibrator-cache ~=0.5.1
    - scipy >=1.11
    - path ~=16.7
    - uncertainties ~=3.1

test:
  imports:
    - component_contribution
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://gitlab.com/equilibrator/component-contribution
  summary: Standard reaction Gibbs energy estimation for biochemical reactions.
  license: MIT
  license_file: LICENSE
  description: >
    Standard reaction Gibbs energy estimation for biochemical reactions.  For more information on the method behind eQuilibrator, please view our open access paper:

    M.E. Beber, M.G. Gollub, D. Mozaffari, K.M. Shebek, A.I. Flamholz, R. Milo, E. Noor (2021) eQuilibrator 3.0: a database solution for thermodynamic constant estimation Nucleic Acids Research [DOI: 10.1093/nar/gkab1106]

    Please, cite this paper if you publish work that uses eQuilibrator.
  dev_url: https://gitlab.com/equilibrator/component-contribution

extra:
  recipe-maintainers:
    - eladnoor
    - Midnighter
